## Creating Array

### Using Array Lib

In [2]:
import array

In [2]:
my_array = array.array('i') #Blank Array
print(my_array)

array('i')


In [3]:
my_array = array.array('i',[1,2,3,4])

In [4]:
print(my_array)

array('i', [1, 2, 3, 4])


In [5]:
my_array.typecode

'i'

In [6]:
len(my_array)

4

### Array using Numpy Lib

In [7]:
import numpy as np

In [8]:
a1 = np.array([],dtype=int)

In [9]:
a1

array([], dtype=int64)

In [10]:
print(a1)

[]


In [11]:
a2 = np.array([1,2,3,4])
print(a2)

[1 2 3 4]


### Insertion in Array

In [12]:
array_1 = array.array('i',[1,2,3,4])
print(array_1)

array('i', [1, 2, 3, 4])


In [13]:
array_1.insert(len(array_1), 0)
print(array_1)

array('i', [1, 2, 3, 4, 0])


### Traversal in Array

In [14]:
def TravrsalArray(array):
    for i in array:
        print(i)

In [15]:
TravrsalArray(array_1)

1
2
3
4
0


In [2]:
import IPython
print(IPython.__version__)

9.1.0


In [3]:
import IPython
print(IPython.__file__)

C:\Users\janinisa\AppData\Local\miniconda3\Lib\site-packages\IPython\__init__.py


In [1]:
import nbformat

path = "Downloads/slm-tiny-stories-Copy2.ipynb"
nb = nbformat.read(path, as_version=nbformat.NO_CONVERT)

if "widgets" in nb.metadata:
    print("Found widgets metadata — removing it to fix export issue.")
    del nb.metadata["widgets"]

nbformat.write(nb, path)
print("Fixed notebook saved.")


Found widgets metadata — removing it to fix export issue.
Fixed notebook saved.


In [3]:
arr = array.array('i',[1,2,3,4,5,6])

In [4]:
def linear_search(array, target):
    for i in range(len(array)):
        if array[i] == target:
            return i
    return -1

In [5]:
print(linear_search(arr, 3))

2


In [6]:
from array import *

In [7]:
# 1) Create an array and traverse

In [33]:
arr_1 = array('i', [1,2,3,4,5,6])

In [34]:
for i in arr_1:
    print(i)

1
2
3
4
5
6


In [35]:
# 2) Access Individual elements through their index

In [36]:
len(arr_1)

6

In [37]:
for idx, i in enumerate(arr_1):
    print(idx, i)

0 1
1 2
2 3
3 4
4 5
5 6


In [38]:
# 3) Append any value using append method

In [39]:
arr_1.append(7)
print(arr_1)

array('i', [1, 2, 3, 4, 5, 6, 7])


In [40]:
# append adds element at end only

In [41]:
#4) insert an element using insert method

In [42]:
arr_1.insert(0,0)
print(arr_1)

array('i', [0, 1, 2, 3, 4, 5, 6, 7])


In [43]:
#5) Extend python array using extend method

In [44]:
arr_2 = array('i',[8,9,10])

In [45]:
arr_1.extend(arr_2)

In [46]:
arr_1

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [47]:
#6) add items from list in array using fromlist() method

In [48]:
lst_1 = [11,12,13]

In [49]:
arr_1.fromlist(lst_1)
print(arr_1)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])


In [50]:
#7) Remove any element from arr using remove method

In [51]:
arr_1.remove(0) #element not index
print(arr_1)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])


In [52]:
arr_1.insert(0,0)
arr_1.insert(len(arr_1),0)

In [53]:
print(arr_1)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0])


In [54]:
arr_1.remove(0)
print(arr_1)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0])


In [55]:
# here it removes first zero only

In [56]:
#8) remove last element of array using pop

In [57]:
arr_1.pop()
print(arr_1)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])


In [60]:
#9) fetch index of any element using index method

In [59]:
print(arr_1.index(3))

2


In [61]:
#10) reverse the array using reverse method

In [69]:
arr_1.reverse()

In [70]:
print(arr_1)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])


In [72]:
for i in range(len(arr_1)//2):
    arr_1[i], arr_1[len(arr_1)-1-i] = arr_1[len(arr_1)-1-i], arr_1[i]

In [73]:
print(arr_1)

array('i', [13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1])


In [78]:
#11) get array buffer information using buffer_info method

In [79]:
arr_1.buffer_info()

(2187580665136, 13)

In [77]:
#12) check of no. occurance using count method

In [83]:
arr_1.append(13)

In [84]:
print(arr_1.count(13))

2


In [85]:
#13) convert array to string using tostring() method

In [90]:
tostr = arr_1.tobytes()
print(tostr)

b'\r\x00\x00\x00\x0c\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\t\x00\x00\x00\x08\x00\x00\x00\x07\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\r\x00\x00\x00'


In [95]:
arr_1

array('i', [13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 13])

In [96]:
#14) converst array to python list using tolist()

In [97]:
arr_1.tolist()
print(arr_1)

array('i', [13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 13])


In [98]:
#15) slicing Array

In [102]:
arr_1[:5], arr_1[5:]

(array('i', [13, 12, 11, 10, 9]), array('i', [8, 7, 6, 5, 4, 3, 2, 1, 13]))

## 2-d array

In [103]:
import numpy as np

In [110]:
twod_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
twod_arr_1 = np.insert(twod_arr, 0, [[10,11,12]], axis = 1)
print(twod_arr_1)

[[10  1  2  3]
 [11  4  5  6]
 [12  7  8  9]]


In [112]:
twod_arr_2 = np.insert(twod_arr_1, 3, [[13,10,11,12]], axis = 0)
print(twod_arr_2)

[[10  1  2  3]
 [11  4  5  6]
 [12  7  8  9]
 [13 10 11 12]]


In [120]:
print(twod_arr_2)

[[10  1  2  3]
 [11  4  5  6]
 [12  7  8  9]
 [13 10 11 12]]


In [121]:
for row in range(twod_arr_2.shape[0]):
    for col in range(twod_arr_2.shape[1]):
        print(twod_arr_2[row][col])

10
1
2
3
11
4
5
6
12
7
8
9
13
10
11
12


In [122]:
for row in range(twod_arr_2.shape[0]):
    for col in range(twod_arr_2.shape[1]):
        if twod_arr_2[row][col] == 10:
            return 'value is located at '+str[row]+" "+str[col]

SyntaxError: 'return' outside function (261352143.py, line 4)